# Generated by Django 5.0.1 on 2024-04-07 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enigme',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=180)),
                ('image', models.CharField(default='default.jpg', max_length=40)),
                ('solution', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Final',
                'verbose_name_plural': 'Finals',
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(max_length=50)),
                ('validee', models.BooleanField(default=False)),
                ('enigme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Enigmes.enigme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'enigme')},
            },
        ),
    ]
