# Generated by Django 5.0.1 on 2024-04-07 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enigme',
            name='numero',
        ),
    ]
