# Generated by Django 5.0.1 on 2024-04-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0002_remove_enigme_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
