# Generated by Django 5.0.1 on 2024-04-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0003_enigme_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
