# Generated by Django 5.0.1 on 2024-05-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0004_alter_enigme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='enigme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enigmes.enigme'),
        ),
    ]
