# Generated by Django 5.0.1 on 2024-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0005_alter_reponse_enigme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='reponse',
            field=models.TextField(),
        ),
    ]
