# Generated by Django 5.0.1 on 2024-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0006_alter_reponse_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponse',
            field=models.CharField(max_length=50),
        ),
    ]
