# Generated by Django 5.0.1 on 2025-01-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0007_alter_enigme_question_alter_reponse_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('nom', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='enigme',
            name='image',
            field=models.CharField(default='default.png', max_length=40),
        ),
    ]
