# Generated by Django 5.0.1 on 2025-01-27 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0008_theme_alter_enigme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigme',
            name='theme',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Enigmes.theme'),
        ),
    ]
