# Generated by Django 5.0.1 on 2025-01-27 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0009_enigme_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='history',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
