# Generated by Django 5.0.1 on 2025-01-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0010_reponse_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigme',
            name='image',
            field=models.ImageField(upload_to='enigme'),
        ),
    ]
