# Generated by Django 5.0.1 on 2025-04-01 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enigmes', '0011_alter_enigme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='final',
            name='theme',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='Enigmes.theme'),
        ),
        migrations.AlterField(
            model_name='enigme',
            name='image',
            field=models.ImageField(default='Enigmes/default.png', upload_to='Enigmes'),
        ),
    ]
